# Generated by Django 5.2 on 2025-05-07 06:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_choise', models.CharField(choices=[('1 Day', '1 Day'), ('3 Month', '3 Month'), ('6 Month', '6 Month')], default='1 Day', max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availabledate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspurance')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('goal', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('have_any_allergy', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO')),
                ('allergy_details', models.CharField(blank=True, max_length=255, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointmentprice')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availabledate')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(unique=True)),
                ('end_time', models.TimeField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availabledate')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('goal', models.TextField()),
                ('any_medical_history', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO')),
                ('medical_history_details', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availabletime')),
            ],
        ),
    ]
