# Generated by Django 5.2 on 2025-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentprice',
            name='actual_price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointmentprice',
            name='offer_price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
