# Generated by Django 5.2 on 2025-05-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_availabletime_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=50),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.TimeField(help_text='Enter time in UK timezone'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.TimeField(help_text='Enter time in UK timezone'),
        ),
    ]
