# Generated by Django 5.2 on 2025-05-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appointmentprice_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentprice',
            name='actual_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointmentprice',
            name='offer_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
